version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mev-postgres
    environment:
      POSTGRES_DB: mevplatform
      POSTGRES_USER: mevuser
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5432:5432'  # Using 5433 instead of 5432 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mevuser -d mevplatform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mev-redis
    ports:
      - '6380:6379'  # Using 6380 instead of 6379 to avoid conflicts
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: mev-network
